# Site settings
title: Besouro Filmes
lang: pt
description: >
  Produtora de filmes e TV em Porto Alegre, Brasil.

contact:
  email: besourofilmes@besourofilmes.com
  facebook: besourofilmes
  vimeo: besourofilmes

collections:
  projects:
    output: true
    permalink: /projects/:name

# Build settings
baseurl: ""
url: "http://www.besourofilmes.com"
permalink: pretty
markdown: kramdown
gems:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
