---
title: Besouro Filmes
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projetos/:name"
    media:
      image: "/assets/projects/images/"
      video: "/assets/projects/videos/"
      trailer: 
    team:
      director: 
      writer: 
      copro: 
    funds:
    - 
  uploads:
    title: Uploads
    output: true
    permalink: "/assets/:name"
description: Produtora de filmes e TV em Porto Alegre, Brasil.
contact:
  email: besourofilmes@besourofilmes.com
  facebook: besourofilmes
  vimeo: besourofilmes
baseurl: 
url: http://besourofilmes.com
permalink: pretty
markdown: kramdown
gems:
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
