# Site settings
title: Besouro Filmes
description: > # this means to ignore newlines until "baseurl:"
  A Besouro Filmes é uma produtora sediada em Porto Alegre, com foco na produção cinematográfica e de conteúdo televisivos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.besourofilmes.com"

contact:
  email: besourofilmes@besourofilmes.com
  facebook: besourofilmes
  vimeo: besourofilmes

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
