---
title: Besouro Filmes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projetos/:name"
  uploads:
    title: Uploads
    output: true
lang: pt
description: 'Produtora de filmes e TV em Porto Alegre, Brasil.

'
contact:
  email: besourofilmes@besourofilmes.com
  facebook: besourofilmes
  vimeo: besourofilmes
baseurl: ''
url: http://besourofilmes.com
permalink: pretty
markdown: kramdown
gems:
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
