# Site settings
title: Besouro Filmes
lang: pt
description: >
  A Besouro Filmes é uma produtora sediada em Porto Alegre, com foco na produção cinematográfica e de conteúdo televisivos.

contact:
  email: besourofilmes@besourofilmes.com
  facebook: besourofilmes
  vimeo: besourofilmes

# Build settings
baseurl: ""
url: "http://www.besourofilmes.com"
markdown: kramdown
gems:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
