---
title: Besouro Filmes
description: Produtora de filmes e TV em Porto Alegre, Brasil.
baseurl:
url: http://besourofilmes.com

contact:
  email: besourofilmes@besourofilmes.com
  facebook: besourofilmes
  vimeo: besourofilmes

timezone: America/Sao_Paulo
permalink: pretty
markdown: kramdown
plugins:
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock

collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projetos/:name/"
    layout: project
  uploads:
    title: Uploads
    output: true
    permalink: "/assets/media/:path"
